// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: protos/openapi.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QryOfString 字符查询条件
type QryOfString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QryOfString) Reset() {
	*x = QryOfString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryOfString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryOfString) ProtoMessage() {}

func (x *QryOfString) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryOfString.ProtoReflect.Descriptor instead.
func (*QryOfString) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{0}
}

func (x *QryOfString) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// QueryLimitOfString 分页查询
type QueryLimitOfString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *QueryLimitOfString) Reset() {
	*x = QueryLimitOfString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLimitOfString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLimitOfString) ProtoMessage() {}

func (x *QueryLimitOfString) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLimitOfString.ProtoReflect.Descriptor instead.
func (*QueryLimitOfString) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLimitOfString) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryLimitOfString) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLimitOfString) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// QryOfStrings Src Paths
type QryOfStrings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []string `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
}

func (x *QryOfStrings) Reset() {
	*x = QryOfStrings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryOfStrings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryOfStrings) ProtoMessage() {}

func (x *QryOfStrings) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryOfStrings.ProtoReflect.Descriptor instead.
func (*QryOfStrings) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{2}
}

func (x *QryOfStrings) GetQuery() []string {
	if x != nil {
		return x.Query
	}
	return nil
}

// ResultOfBool Bool Result
type ResultOfBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResultOfBool) Reset() {
	*x = ResultOfBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultOfBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultOfBool) ProtoMessage() {}

func (x *ResultOfBool) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultOfBool.ProtoReflect.Descriptor instead.
func (*ResultOfBool) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{3}
}

func (x *ResultOfBool) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ResultOfBool) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ResultOfInt64 Int64 Result
type ResultOfInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResultOfInt64) Reset() {
	*x = ResultOfInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultOfInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultOfInt64) ProtoMessage() {}

func (x *ResultOfInt64) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultOfInt64.ProtoReflect.Descriptor instead.
func (*ResultOfInt64) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{4}
}

func (x *ResultOfInt64) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// ResultOfString String Result
type ResultOfString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResultOfString) Reset() {
	*x = ResultOfString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultOfString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultOfString) ProtoMessage() {}

func (x *ResultOfString) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultOfString.ProtoReflect.Descriptor instead.
func (*ResultOfString) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{5}
}

func (x *ResultOfString) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// RenameCmd 重命名
type RenameCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *RenameCmd) Reset() {
	*x = RenameCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameCmd) ProtoMessage() {}

func (x *RenameCmd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameCmd.ProtoReflect.Descriptor instead.
func (*RenameCmd) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{6}
}

func (x *RenameCmd) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *RenameCmd) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

// MoveCmd move
type MoveCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src      string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst      string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Override bool   `protobuf:"varint,3,opt,name=override,proto3" json:"override,omitempty"`
}

func (x *MoveCmd) Reset() {
	*x = MoveCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCmd) ProtoMessage() {}

func (x *MoveCmd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCmd.ProtoReflect.Descriptor instead.
func (*MoveCmd) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{7}
}

func (x *MoveCmd) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MoveCmd) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *MoveCmd) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

// CopyCmd move
type CopyCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src      string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst      string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Override bool   `protobuf:"varint,3,opt,name=override,proto3" json:"override,omitempty"`
}

func (x *CopyCmd) Reset() {
	*x = CopyCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyCmd) ProtoMessage() {}

func (x *CopyCmd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyCmd.ProtoReflect.Descriptor instead.
func (*CopyCmd) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{8}
}

func (x *CopyCmd) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyCmd) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *CopyCmd) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

// SubmitTokenCmd 提交token
type SubmitTokenCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Override bool   `protobuf:"varint,2,opt,name=override,proto3" json:"override,omitempty"`
}

func (x *SubmitTokenCmd) Reset() {
	*x = SubmitTokenCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTokenCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTokenCmd) ProtoMessage() {}

func (x *SubmitTokenCmd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTokenCmd.ProtoReflect.Descriptor instead.
func (*SubmitTokenCmd) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitTokenCmd) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SubmitTokenCmd) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

// QryStreamURLCmd 查询流URL
type QryStreamURLCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeNo   string `protobuf:"bytes,1,opt,name=nodeNo,proto3" json:"nodeNo,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (x *QryStreamURLCmd) Reset() {
	*x = QryStreamURLCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryStreamURLCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryStreamURLCmd) ProtoMessage() {}

func (x *QryStreamURLCmd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryStreamURLCmd.ProtoReflect.Descriptor instead.
func (*QryStreamURLCmd) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{10}
}

func (x *QryStreamURLCmd) GetNodeNo() string {
	if x != nil {
		return x.NodeNo
	}
	return ""
}

func (x *QryStreamURLCmd) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *QryStreamURLCmd) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// TNode 元数据内容(filenames)
type TNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid   string `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Addr  string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Flag  int32  `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	Name  string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Size  int64  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Ctime int64  `protobuf:"varint,7,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime int64  `protobuf:"varint,8,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Props string `protobuf:"bytes,9,opt,name=props,proto3" json:"props,omitempty"`
}

func (x *TNode) Reset() {
	*x = TNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TNode) ProtoMessage() {}

func (x *TNode) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TNode.ProtoReflect.Descriptor instead.
func (*TNode) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{11}
}

func (x *TNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TNode) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *TNode) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *TNode) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *TNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TNode) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TNode) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *TNode) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *TNode) GetProps() string {
	if x != nil {
		return x.Props
	}
	return ""
}

// StreamToken 流操作Token
type StreamToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NodeNo   string `protobuf:"bytes,2,opt,name=nodeNo,proto3" json:"nodeNo,omitempty"`
	FileID   string `protobuf:"bytes,3,opt,name=fileID,proto3" json:"fileID,omitempty"`
	FilePath string `protobuf:"bytes,4,opt,name=filePath,proto3" json:"filePath,omitempty"`
	FileSize int64  `protobuf:"varint,5,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	CTime    int64  `protobuf:"varint,6,opt,name=cTime,proto3" json:"cTime,omitempty"`
	MTime    int64  `protobuf:"varint,7,opt,name=mTime,proto3" json:"mTime,omitempty"`
	EndPoint string `protobuf:"bytes,8,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	Type     int32  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *StreamToken) Reset() {
	*x = StreamToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamToken) ProtoMessage() {}

func (x *StreamToken) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamToken.ProtoReflect.Descriptor instead.
func (*StreamToken) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{12}
}

func (x *StreamToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StreamToken) GetNodeNo() string {
	if x != nil {
		return x.NodeNo
	}
	return ""
}

func (x *StreamToken) GetFileID() string {
	if x != nil {
		return x.FileID
	}
	return ""
}

func (x *StreamToken) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *StreamToken) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *StreamToken) GetCTime() int64 {
	if x != nil {
		return x.CTime
	}
	return 0
}

func (x *StreamToken) GetMTime() int64 {
	if x != nil {
		return x.MTime
	}
	return 0
}

func (x *StreamToken) GetEndPoint() string {
	if x != nil {
		return x.EndPoint
	}
	return ""
}

func (x *StreamToken) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// SrcAndDstBo src 和 dst
type SrcAndDstBo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *SrcAndDstBo) Reset() {
	*x = SrcAndDstBo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrcAndDstBo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrcAndDstBo) ProtoMessage() {}

func (x *SrcAndDstBo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrcAndDstBo.ProtoReflect.Descriptor instead.
func (*SrcAndDstBo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{13}
}

func (x *SrcAndDstBo) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *SrcAndDstBo) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

// CopyNodeBo 拷贝
type CopyNodeBo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src      string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst      string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Override bool   `protobuf:"varint,3,opt,name=override,proto3" json:"override,omitempty"`
}

func (x *CopyNodeBo) Reset() {
	*x = CopyNodeBo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyNodeBo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyNodeBo) ProtoMessage() {}

func (x *CopyNodeBo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyNodeBo.ProtoReflect.Descriptor instead.
func (*CopyNodeBo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{14}
}

func (x *CopyNodeBo) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyNodeBo) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *CopyNodeBo) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

// MoveNodeBo 移动
type MoveNodeBo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src      string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst      string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Override bool   `protobuf:"varint,3,opt,name=override,proto3" json:"override,omitempty"`
}

func (x *MoveNodeBo) Reset() {
	*x = MoveNodeBo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveNodeBo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveNodeBo) ProtoMessage() {}

func (x *MoveNodeBo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveNodeBo.ProtoReflect.Descriptor instead.
func (*MoveNodeBo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{15}
}

func (x *MoveNodeBo) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MoveNodeBo) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *MoveNodeBo) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

// WriteTokenBo 文件上传递交token
type WriteTokenBo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Override bool   `protobuf:"varint,2,opt,name=override,proto3" json:"override,omitempty"`
}

func (x *WriteTokenBo) Reset() {
	*x = WriteTokenBo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteTokenBo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTokenBo) ProtoMessage() {}

func (x *WriteTokenBo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTokenBo.ProtoReflect.Descriptor instead.
func (*WriteTokenBo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{16}
}

func (x *WriteTokenBo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WriteTokenBo) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

// LimitQueryBo 分页查询
type LimitQueryBo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *LimitQueryBo) Reset() {
	*x = LimitQueryBo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitQueryBo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitQueryBo) ProtoMessage() {}

func (x *LimitQueryBo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitQueryBo.ProtoReflect.Descriptor instead.
func (*LimitQueryBo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{17}
}

func (x *LimitQueryBo) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *LimitQueryBo) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LimitQueryBo) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// CreateUserBo 用户表存储的结构
type CreateUserBo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserType int32  `protobuf:"varint,1,opt,name=userType,proto3" json:"userType,omitempty"`
	UserID   string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	UserPWD  string `protobuf:"bytes,4,opt,name=userPWD,proto3" json:"userPWD,omitempty"`
}

func (x *CreateUserBo) Reset() {
	*x = CreateUserBo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserBo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserBo) ProtoMessage() {}

func (x *CreateUserBo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserBo.ProtoReflect.Descriptor instead.
func (*CreateUserBo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{18}
}

func (x *CreateUserBo) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

func (x *CreateUserBo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateUserBo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserBo) GetUserPWD() string {
	if x != nil {
		return x.UserPWD
	}
	return ""
}

// PwdUpdateBo 更改用户密码
type PwdUpdateBo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pwd  string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *PwdUpdateBo) Reset() {
	*x = PwdUpdateBo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwdUpdateBo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwdUpdateBo) ProtoMessage() {}

func (x *PwdUpdateBo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwdUpdateBo.ProtoReflect.Descriptor instead.
func (*PwdUpdateBo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{19}
}

func (x *PwdUpdateBo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PwdUpdateBo) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

// UserListDto 用户信息列表
type UserListDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []*UserInfo `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
	Total int64       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *UserListDto) Reset() {
	*x = UserListDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListDto) ProtoMessage() {}

func (x *UserListDto) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListDto.ProtoReflect.Descriptor instead.
func (*UserListDto) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{20}
}

func (x *UserListDto) GetDatas() []*UserInfo {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *UserListDto) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UserInfo 用户表存储的结构
type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserType int32  `protobuf:"varint,1,opt,name=userType,proto3" json:"userType,omitempty"`
	UserID   string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	CtTime   int64  `protobuf:"varint,4,opt,name=ctTime,proto3" json:"ctTime,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{21}
}

func (x *UserInfo) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetCtTime() int64 {
	if x != nil {
		return x.CtTime
	}
	return 0
}

// DirNameListDto 文件夹目录列表
type DirNameListDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []string `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
	Total int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DirNameListDto) Reset() {
	*x = DirNameListDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirNameListDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirNameListDto) ProtoMessage() {}

func (x *DirNameListDto) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirNameListDto.ProtoReflect.Descriptor instead.
func (*DirNameListDto) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{22}
}

func (x *DirNameListDto) GetDatas() []string {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *DirNameListDto) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// DirNodeListDto 文件夹目录列表
type DirNodeListDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []*TNode `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
	Total int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DirNodeListDto) Reset() {
	*x = DirNodeListDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_openapi_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirNodeListDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirNodeListDto) ProtoMessage() {}

func (x *DirNodeListDto) ProtoReflect() protoreflect.Message {
	mi := &file_protos_openapi_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirNodeListDto.ProtoReflect.Descriptor instead.
func (*DirNodeListDto) Descriptor() ([]byte, []int) {
	return file_protos_openapi_proto_rawDescGZIP(), []int{23}
}

func (x *DirNodeListDto) GetDatas() []*TNode {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *DirNodeListDto) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_protos_openapi_proto protoreflect.FileDescriptor

var file_protos_openapi_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x23, 0x0a, 0x0b, 0x51, 0x72, 0x79, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x58, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x24,
	0x0a, 0x0c, 0x51, 0x72, 0x79, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x40, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66,
	0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4f, 0x66, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x28, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2f, 0x0a, 0x09, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x07, 0x4d, 0x6f,
	0x76, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65,
	0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x76, 0x65,
	0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x49, 0x0a, 0x07, 0x43, 0x6f, 0x70, 0x79, 0x43, 0x6d, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x64, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65,
	0x22, 0x42, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43,
	0x6d, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x22, 0x5b, 0x0a, 0x0f, 0x51, 0x72, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x55, 0x52, 0x4c, 0x43, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x4e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x22, 0xbb, 0x01, 0x0a, 0x05, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x70, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x22,
	0xe7, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x53, 0x72, 0x63,
	0x41, 0x6e, 0x64, 0x44, 0x73, 0x74, 0x42, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x0a,
	0x43, 0x6f, 0x70, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x4c, 0x0a, 0x0a, 0x4d, 0x6f,
	0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x52, 0x0a, 0x0c, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x78,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x50, 0x57, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x50, 0x57, 0x44, 0x22, 0x33, 0x0a, 0x0b, 0x50, 0x77, 0x64, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x4c, 0x0a,
	0x0b, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x74, 0x6f, 0x12, 0x27, 0x0a, 0x05,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x72, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x3c, 0x0a, 0x0e, 0x44, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x74,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x4c, 0x0a,
	0x0e, 0x44, 0x69, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x74, 0x6f, 0x12,
	0x24, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xe7, 0x09, 0x0a, 0x07,
	0x4f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x69, 0x12, 0x36, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72,
	0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x4f, 0x66,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12,
	0x37, 0x0a, 0x06, 0x49, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a,
	0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x49, 0x73, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72,
	0x79, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6c,
	0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x4f,
	0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x22,
	0x00, 0x12, 0x31, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x1a, 0x0e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x4e, 0x6f,
	0x64, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x4f, 0x66,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x44, 0x69, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x74, 0x6f,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x69, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x17, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x69, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x44, 0x6f, 0x4d, 0x6b, 0x44, 0x69,
	0x72, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x4f,
	0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x22, 0x00, 0x12, 0x39, 0x0a, 0x08, 0x44, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x4f, 0x66, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x37, 0x0a,
	0x08, 0x44, 0x6f, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x6d, 0x64, 0x1a, 0x15, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66,
	0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x44, 0x6f, 0x43, 0x6f, 0x70, 0x79,
	0x12, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x43,
	0x6d, 0x64, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x33, 0x0a,
	0x06, 0x44, 0x6f, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x43, 0x6d, 0x64, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6c,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0c, 0x44, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79,
	0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x0e, 0x44, 0x6f, 0x41, 0x73, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79,
	0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x0f, 0x44, 0x6f, 0x41, 0x73, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72,
	0x79, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x00, 0x12, 0x3e, 0x0a, 0x0e, 0x44, 0x6f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72,
	0x79, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x12, 0x44, 0x6f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6d, 0x64,
	0x1a, 0x0e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x4e, 0x6f, 0x64, 0x65,
	0x22, 0x00, 0x12, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x51, 0x72, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x55, 0x52, 0x4c, 0x43, 0x6d, 0x64,
	0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x55, 0x52, 0x4c,
	0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x72, 0x79, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x55, 0x52, 0x4c, 0x43, 0x6d, 0x64, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_openapi_proto_rawDescOnce sync.Once
	file_protos_openapi_proto_rawDescData = file_protos_openapi_proto_rawDesc
)

func file_protos_openapi_proto_rawDescGZIP() []byte {
	file_protos_openapi_proto_rawDescOnce.Do(func() {
		file_protos_openapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_openapi_proto_rawDescData)
	})
	return file_protos_openapi_proto_rawDescData
}

var file_protos_openapi_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_protos_openapi_proto_goTypes = []interface{}{
	(*QryOfString)(nil),        // 0: service.QryOfString
	(*QueryLimitOfString)(nil), // 1: service.QueryLimitOfString
	(*QryOfStrings)(nil),       // 2: service.QryOfStrings
	(*ResultOfBool)(nil),       // 3: service.ResultOfBool
	(*ResultOfInt64)(nil),      // 4: service.ResultOfInt64
	(*ResultOfString)(nil),     // 5: service.ResultOfString
	(*RenameCmd)(nil),          // 6: service.RenameCmd
	(*MoveCmd)(nil),            // 7: service.MoveCmd
	(*CopyCmd)(nil),            // 8: service.CopyCmd
	(*SubmitTokenCmd)(nil),     // 9: service.SubmitTokenCmd
	(*QryStreamURLCmd)(nil),    // 10: service.QryStreamURLCmd
	(*TNode)(nil),              // 11: service.TNode
	(*StreamToken)(nil),        // 12: service.StreamToken
	(*SrcAndDstBo)(nil),        // 13: service.SrcAndDstBo
	(*CopyNodeBo)(nil),         // 14: service.CopyNodeBo
	(*MoveNodeBo)(nil),         // 15: service.MoveNodeBo
	(*WriteTokenBo)(nil),       // 16: service.WriteTokenBo
	(*LimitQueryBo)(nil),       // 17: service.LimitQueryBo
	(*CreateUserBo)(nil),       // 18: service.CreateUserBo
	(*PwdUpdateBo)(nil),        // 19: service.PwdUpdateBo
	(*UserListDto)(nil),        // 20: service.UserListDto
	(*UserInfo)(nil),           // 21: service.UserInfo
	(*DirNameListDto)(nil),     // 22: service.DirNameListDto
	(*DirNodeListDto)(nil),     // 23: service.DirNodeListDto
}
var file_protos_openapi_proto_depIdxs = []int32{
	21, // 0: service.UserListDto.datas:type_name -> service.UserInfo
	11, // 1: service.DirNodeListDto.datas:type_name -> service.TNode
	0,  // 2: service.OpenApi.IsDir:input_type -> service.QryOfString
	0,  // 3: service.OpenApi.IsFile:input_type -> service.QryOfString
	0,  // 4: service.OpenApi.IsExist:input_type -> service.QryOfString
	0,  // 5: service.OpenApi.GetFileSize:input_type -> service.QryOfString
	0,  // 6: service.OpenApi.GetNode:input_type -> service.QryOfString
	2,  // 7: service.OpenApi.GetNodes:input_type -> service.QryOfStrings
	1,  // 8: service.OpenApi.GetDirNameList:input_type -> service.QueryLimitOfString
	1,  // 9: service.OpenApi.GetDirNodeList:input_type -> service.QueryLimitOfString
	0,  // 10: service.OpenApi.DoMkDir:input_type -> service.QryOfString
	0,  // 11: service.OpenApi.DoDelete:input_type -> service.QryOfString
	6,  // 12: service.OpenApi.DoRename:input_type -> service.RenameCmd
	7,  // 13: service.OpenApi.DoCopy:input_type -> service.MoveCmd
	8,  // 14: service.OpenApi.DoMove:input_type -> service.CopyCmd
	0,  // 15: service.OpenApi.DoQueryToken:input_type -> service.QryOfString
	0,  // 16: service.OpenApi.DoAskReadToken:input_type -> service.QryOfString
	0,  // 17: service.OpenApi.DoAskWriteToken:input_type -> service.QryOfString
	0,  // 18: service.OpenApi.DoRefreshToken:input_type -> service.QryOfString
	9,  // 19: service.OpenApi.DoSubmitWriteToken:input_type -> service.SubmitTokenCmd
	10, // 20: service.OpenApi.GetReadStreamURL:input_type -> service.QryStreamURLCmd
	10, // 21: service.OpenApi.GetWriteStreamURL:input_type -> service.QryStreamURLCmd
	3,  // 22: service.OpenApi.IsDir:output_type -> service.ResultOfBool
	3,  // 23: service.OpenApi.IsFile:output_type -> service.ResultOfBool
	3,  // 24: service.OpenApi.IsExist:output_type -> service.ResultOfBool
	4,  // 25: service.OpenApi.GetFileSize:output_type -> service.ResultOfInt64
	11, // 26: service.OpenApi.GetNode:output_type -> service.TNode
	23, // 27: service.OpenApi.GetNodes:output_type -> service.DirNodeListDto
	22, // 28: service.OpenApi.GetDirNameList:output_type -> service.DirNameListDto
	23, // 29: service.OpenApi.GetDirNodeList:output_type -> service.DirNodeListDto
	5,  // 30: service.OpenApi.DoMkDir:output_type -> service.ResultOfString
	3,  // 31: service.OpenApi.DoDelete:output_type -> service.ResultOfBool
	3,  // 32: service.OpenApi.DoRename:output_type -> service.ResultOfBool
	5,  // 33: service.OpenApi.DoCopy:output_type -> service.ResultOfString
	3,  // 34: service.OpenApi.DoMove:output_type -> service.ResultOfBool
	12, // 35: service.OpenApi.DoQueryToken:output_type -> service.StreamToken
	12, // 36: service.OpenApi.DoAskReadToken:output_type -> service.StreamToken
	12, // 37: service.OpenApi.DoAskWriteToken:output_type -> service.StreamToken
	12, // 38: service.OpenApi.DoRefreshToken:output_type -> service.StreamToken
	11, // 39: service.OpenApi.DoSubmitWriteToken:output_type -> service.TNode
	5,  // 40: service.OpenApi.GetReadStreamURL:output_type -> service.ResultOfString
	5,  // 41: service.OpenApi.GetWriteStreamURL:output_type -> service.ResultOfString
	22, // [22:42] is the sub-list for method output_type
	2,  // [2:22] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protos_openapi_proto_init() }
func file_protos_openapi_proto_init() {
	if File_protos_openapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_openapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryOfString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLimitOfString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryOfStrings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultOfBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultOfInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultOfString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTokenCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryStreamURLCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrcAndDstBo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyNodeBo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveNodeBo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteTokenBo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitQueryBo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserBo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwdUpdateBo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserListDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirNameListDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_openapi_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirNodeListDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_openapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_openapi_proto_goTypes,
		DependencyIndexes: file_protos_openapi_proto_depIdxs,
		MessageInfos:      file_protos_openapi_proto_msgTypes,
	}.Build()
	File_protos_openapi_proto = out.File
	file_protos_openapi_proto_rawDesc = nil
	file_protos_openapi_proto_goTypes = nil
	file_protos_openapi_proto_depIdxs = nil
}
