// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: dto_comm.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QryOfString 字符查询条件
type QryOfString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QryOfString) Reset() {
	*x = QryOfString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dto_comm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryOfString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryOfString) ProtoMessage() {}

func (x *QryOfString) ProtoReflect() protoreflect.Message {
	mi := &file_dto_comm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryOfString.ProtoReflect.Descriptor instead.
func (*QryOfString) Descriptor() ([]byte, []int) {
	return file_dto_comm_proto_rawDescGZIP(), []int{0}
}

func (x *QryOfString) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// QueryLimitOfString 分页查询
type QueryLimitOfString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *QueryLimitOfString) Reset() {
	*x = QueryLimitOfString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dto_comm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLimitOfString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLimitOfString) ProtoMessage() {}

func (x *QueryLimitOfString) ProtoReflect() protoreflect.Message {
	mi := &file_dto_comm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLimitOfString.ProtoReflect.Descriptor instead.
func (*QueryLimitOfString) Descriptor() ([]byte, []int) {
	return file_dto_comm_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLimitOfString) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryLimitOfString) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLimitOfString) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// QryOfStrings Src Paths
type QryOfStrings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query []string `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
}

func (x *QryOfStrings) Reset() {
	*x = QryOfStrings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dto_comm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryOfStrings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryOfStrings) ProtoMessage() {}

func (x *QryOfStrings) ProtoReflect() protoreflect.Message {
	mi := &file_dto_comm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryOfStrings.ProtoReflect.Descriptor instead.
func (*QryOfStrings) Descriptor() ([]byte, []int) {
	return file_dto_comm_proto_rawDescGZIP(), []int{2}
}

func (x *QryOfStrings) GetQuery() []string {
	if x != nil {
		return x.Query
	}
	return nil
}

// ResultOfBool Bool Result
type ResultOfBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResultOfBool) Reset() {
	*x = ResultOfBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dto_comm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultOfBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultOfBool) ProtoMessage() {}

func (x *ResultOfBool) ProtoReflect() protoreflect.Message {
	mi := &file_dto_comm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultOfBool.ProtoReflect.Descriptor instead.
func (*ResultOfBool) Descriptor() ([]byte, []int) {
	return file_dto_comm_proto_rawDescGZIP(), []int{3}
}

func (x *ResultOfBool) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ResultOfBool) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ResultOfInt64 Int64 Result
type ResultOfInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResultOfInt64) Reset() {
	*x = ResultOfInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dto_comm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultOfInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultOfInt64) ProtoMessage() {}

func (x *ResultOfInt64) ProtoReflect() protoreflect.Message {
	mi := &file_dto_comm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultOfInt64.ProtoReflect.Descriptor instead.
func (*ResultOfInt64) Descriptor() ([]byte, []int) {
	return file_dto_comm_proto_rawDescGZIP(), []int{4}
}

func (x *ResultOfInt64) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// ResultOfString String Result
type ResultOfString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResultOfString) Reset() {
	*x = ResultOfString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dto_comm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultOfString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultOfString) ProtoMessage() {}

func (x *ResultOfString) ProtoReflect() protoreflect.Message {
	mi := &file_dto_comm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultOfString.ProtoReflect.Descriptor instead.
func (*ResultOfString) Descriptor() ([]byte, []int) {
	return file_dto_comm_proto_rawDescGZIP(), []int{5}
}

func (x *ResultOfString) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_dto_comm_proto protoreflect.FileDescriptor

var file_dto_comm_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x64, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0b, 0x51, 0x72, 0x79, 0x4f, 0x66, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x58, 0x0a, 0x12, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x22, 0x24, 0x0a, 0x0c, 0x51, 0x72, 0x79, 0x4f, 0x66, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x40, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x66, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f,
	0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x10, 0x5a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x74, 0x6f, 0x3b, 0x64, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dto_comm_proto_rawDescOnce sync.Once
	file_dto_comm_proto_rawDescData = file_dto_comm_proto_rawDesc
)

func file_dto_comm_proto_rawDescGZIP() []byte {
	file_dto_comm_proto_rawDescOnce.Do(func() {
		file_dto_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_dto_comm_proto_rawDescData)
	})
	return file_dto_comm_proto_rawDescData
}

var file_dto_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dto_comm_proto_goTypes = []interface{}{
	(*QryOfString)(nil),        // 0: dto.QryOfString
	(*QueryLimitOfString)(nil), // 1: dto.QueryLimitOfString
	(*QryOfStrings)(nil),       // 2: dto.QryOfStrings
	(*ResultOfBool)(nil),       // 3: dto.ResultOfBool
	(*ResultOfInt64)(nil),      // 4: dto.ResultOfInt64
	(*ResultOfString)(nil),     // 5: dto.ResultOfString
}
var file_dto_comm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dto_comm_proto_init() }
func file_dto_comm_proto_init() {
	if File_dto_comm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dto_comm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryOfString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dto_comm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLimitOfString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dto_comm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryOfStrings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dto_comm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultOfBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dto_comm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultOfInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dto_comm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultOfString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dto_comm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dto_comm_proto_goTypes,
		DependencyIndexes: file_dto_comm_proto_depIdxs,
		MessageInfos:      file_dto_comm_proto_msgTypes,
	}.Build()
	File_dto_comm_proto = out.File
	file_dto_comm_proto_rawDesc = nil
	file_dto_comm_proto_goTypes = nil
	file_dto_comm_proto_depIdxs = nil
}
